- hosts: all
  become: yes
  tasks:
    - name: copy the docker compose file
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: absent
      become_user: ubuntu
    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
      become_user: ubuntu
      register: output
    - name: Show results
      ansible.builting.debug:
        var: output