name: Docker Publish to GHCR

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["lint and test flask app"]
        types:
            - completed

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Docker login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker Image
              run: docker build -t ghcr.io/loise/linter-python-flask/monapp:latest .
            - name: Push Docker Image to GHCR
              run: docker push ghcr.io/loise/linter-python-flask/monapp:latest